---
version: 3
images:
  base_image:
    name: aap261.lan/ee-minimal-rhel9:latest
dependencies:
  galaxy: requirements.yml
  system:
    - python3-pip
  python:
    - dumb-init==1.2.5

additional_build_files:
  - src: files/ansible.cfg
    dest: configs

...
